os:
  - Visual Studio 2017

init:
  - git config --global core.autocrlf input
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

environment:
  TF_CODE_FOLDER: '%APPVEYOR_BUILD_FOLDER%\tf_code'

install:
  - git clone --branch=v1.13.1 https://github.com/tensorflow/tensorflow.git %TF_CODE_FOLDER%
  - cd %TF_CODE_FOLDER%
  - C:\Python37-x64\python -m venv %APPVEYOR_BUILD_FOLDER% # https://www.appveyor.com/docs/windows-images-software/#python
  - pip install six numpy wheel
  - pip install keras_applications==1.0.6 --no-deps
  - pip install keras_preprocessing==1.0.5 --no-deps
  - choco install mono
  - choco install bazel
  - choco install patch
  - choco install unzip
  # - set PATH=C:\tools\msys64\usr\bin;%PATH%
  # - pacman -q -S git patch unzip

cache:
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  # - '%TF_CODE_FOLDER%'

build_script:
  - cd %TF_CODE_FOLDER%
  - dir
  - python ./configure.py
  - cd %APPVEYOR_BUILD_FOLDER%/tensorflow/tools/ci_build/windows/
  - sh libtensorflow_cpu.sh

notifications:
- provider: Slack
  auth_token:
    secure: '%SLACK_API_CLIENT_SECRET%'
  channel: '#tensorflowbuild'
