os:
  - Visual Studio 2015

init:
  - git config --global core.autocrlf input
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

environment:
  TF_CODE_FOLDER: '%APPVEYOR_BUILD_FOLDER%\tf_code'

install:
  - which python
  - IF NOT EXIST %TF_CODE_FOLDER% (
      git clone --branch=v1.13.1 https://github.com/tensorflow/tensorflow.git %TF_CODE_FOLDER% )
  - cd %TF_CODE_FOLDER%
  - git submodule update --init --recursive
  # - C:\Python37-x64\python -m venv %APPVEYOR_BUILD_FOLDER% # https://www.appveyor.com/docs/windows-images-software/#python
  - set PATH=C:\Python37-x64;%PATH%
  - which python
  - python -m pip install six numpy wheel
  - python -m pip install keras_applications==1.0.6 --no-deps
  - python -m pip install keras_preprocessing==1.0.5 --no-deps
  - python -m pip install swiglpk
  - choco install mono
  - choco install bazel --version 0.21.0
  - choco install swig
  ### instead of pacman -q -S git patch unzip
  # - choco install patch
  # - choco install unzip

# cache:
#   - C:\ProgramData\chocolatey\lib -> appveyor.yml
#   - C:\ProgramData\chocolatey\bin -> appveyor.yml
#   - '%TF_CODE_FOLDER%'

build_script:
  - cd %TF_CODE_FOLDER%
  - dir
  - dir C:\Python37-x64\libs
  ###
  # - set PY_EXE="C:\Python37-x64\python.exe"
  # - set PY_LIB="C:\Python37-x64\libs\python37.lib"
  # - set PIP_EXE="C:\Python37-x64\Scripts\pip.exe"
  # - set CMAKE_EXE="C:\Program Files (x86)\CMake\bin\cmake"
  # - set REPO_ROOT=%TF_CODE_FOLDER%
  # - set SWIG_EXE=C:\ProgramData\chocolatey\bin\swig
  # - python %TF_CODE_FOLDER%\tensorflow\tools\git\gen_git_source.py --raw_generate %TF_CODE_FOLDER%/tensorflow/core/util/version_info.cc
  # - tensorflow\tools\ci_build\windows\cpu\cmake\run_build.bat
  ###
  - cd %TF_CODE_FOLDER%
  - move /Y %APPVEYOR_BUILD_FOLDER%/tools/lib_package/BUILD %TF_CODE_FOLDER%/tools/lib_package
  - set PYTHON_DIRECTORY=Python37-x64
  - cd %TF_CODE_FOLDER%/tensorflow/tools/ci_build/windows/
  - sh libtensorflow_cpu.sh

notifications:
- provider: Slack
  incoming_webhook:
    secure: Sulkkyq57PP9HQWoRZKZJpw+XELOyFf6DElq7gZrTZQTLWg3rYUIHpnrI1FU9QJhyt/BmO5DgBHqWuIWmiKLAMqyetmET4KsdI43gvgGU0Q=
