#-------------------#
#   itkTensorFlow   #
#-------------------#

os:
  - Visual Studio 2017

init:
  - git config --global core.autocrlf input
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

clone_script:
  - cmd: git clone --branch=v1.13.1 https://github.com/tensorflow/tensorflow.git %APPVEYOR_BUILD_FOLDER%
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: dir

install:
  - choco install mono
  - choco install bazel
  - set PATH=C:\Python37-x64;%PATH% # https://www.appveyor.com/docs/windows-images-software/#python
  - pip3 install six numpy wheel
  - pip3 install keras_applications==1.0.6 --no-deps
  - pip3 install keras_preprocessing==1.0.5 --no-deps
  - pacman -S git patch unzip

build_script:
  - python ./configure.py
  - cd %APPVEYOR_BUILD_FOLDER%/tensorflow/tools/ci_build/windows/
  - sh libtensorflow_cpu.sh
