os:
  - Visual Studio 2017

init:
  - git config --global core.autocrlf input
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

clone_script:
  - cmd: git clone --branch=v1.13.1 https://github.com/tensorflow/tensorflow.git %APPVEYOR_BUILD_FOLDER%
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: dir

install:
  - virtualenv -p C:\Python37-x64\python.exe %APPVEYOR_BUILD_FOLDER%# https://www.appveyor.com/docs/windows-images-software/#python
  - cd %APPVEYOR_BUILD_FOLDER%
  - venv\Scripts\activate
  - pip install six numpy wheel
  - pip install keras_applications==1.0.6 --no-deps
  - pip install keras_preprocessing==1.0.5 --no-deps
  - choco install mono
  - choco install bazel
  - pacman -S git patch unzip

cache:
  - C:\ProgramData\chocolatey\mono -> appveyor.yml
  - C:\ProgramData\chocolatey\bazel -> appveyor.yml

build_script:
  - python ./configure.py
  - cd %APPVEYOR_BUILD_FOLDER%/tensorflow/tools/ci_build/windows/
  - sh libtensorflow_cpu.sh
